### ISSUE TITLE
Error when trying to deploy to bucket in Frankfurt

### ISSUE THREAD

**Issue by sarjanen** [ember-cli-deploy/ember-cli-deploy#15]
Just created a new bucket with the Frankfurt region and getting this error message when trying to deploy:

```
Unable to sync: InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
    at Request.extractError (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/services/s3.js:343:35)
    at Request.callListeners (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/request.js:604:14)
    at Request.transition (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/request.js:21:12)
    at AcceptorStateMachine.runTo (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/request.js:22:9)
    at Request.<anonymous> (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/request.js:606:12)
    at Request.callListeners (/frontend/node_modules/ember-deploy/node_modules/s3/node_modules/aws-sdk/lib/sequential_executor.js:104:18)
```

Everything worked fine when I was using Oregon as bucket region.

**Comment by MikeAski** [comment]
@LevelbossMike why did you close the issue, as it is pending, while referenced ones are still open?

**Comment by LevelbossMike** [comment]
@MikeAski 

'I suggest we wait until this is fixed in node-s3-client and work around the issue by using a different region (Frankfurt seems to be special in s3 terms).'

There's really nothing ember-deploy-s3 can do to fix this. As stated above it shouldn't make a difference if you used a different region than frankfurt

**Comment by MikeAski** [comment]
Well, we switched to ireland, indeed. Thx for your reply
