### ISSUE TITLE
Occasional build error

### ISSUE THREAD

**Issue by elidupuis** [ember-cli-deploy/ember-cli-deploy#391]
I've been getting this error every now and then... opening this issue in order to collect clues and narrow in on the issue.

```shell
Elis-MacBook-Pro:admin eli$ ember deploy --activate qa
version: 2.4.2
- build failed
Error: ENOENT: no such file or directory, open '/Users/eli/showbie/admin/tmp/deploy-dist/assets/admin.css'
Error: ENOENT: no such file or directory, open '/Users/eli/showbie/admin/tmp/deploy-dist/assets/admin.css'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at TreeSync.<anonymous> (/Users/eli/showbie/admin/node_modules/ember-cli/node_modules/tree-sync/index.js:59:19)
    at Array.forEach (native)
    at TreeSync.sync (/Users/eli/showbie/admin/node_modules/ember-cli/node_modules/tree-sync/index.js:50:14)
    at Class.module.exports.Task.extend.copyToOutputPath (/Users/eli/showbie/admin/node_modules/ember-cli/lib/models/builder.js:124:10)
    at /Users/eli/showbie/admin/node_modules/ember-cli/lib/models/builder.js:132:21
    at lib$rsvp$$internal$$tryCatch (/Users/eli/showbie/admin/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/eli/showbie/admin/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/eli/showbie/admin/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/eli/showbie/admin/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)fs.js:60
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, rmdir '/Users/eli/showbie/admin/tmp/deploy-dist/assets'
    at Error (native)
```

I'll try to consistently reproduce the error using `--verbose`.

**Comment by ghedamat** [comment]
@elidupuis if I'm reading the stacktrace correctly this is a build error so it's probably more related to your project and/or ember-cli than the deploy aspect.

I'll close this for now but if you can produce a reproducing scenario I'm happy to discuss/try to troubleshoot with you
