### ISSUE TITLE
Error in unavailable plugin error

### ISSUE THREAD

**Issue by dschmidt** [ember-cli-deploy/ember-cli-deploy#393]
When you reference a plugin that is not installed, you end up in this code path https://github.com/ember-cli-deploy/ember-cli-deploy/blob/master/lib/tasks/pipeline.js#L115 which itself triggers an error instead of printing out the actual problem:

```
Cannot convert object to primitive value
TypeError: Cannot convert object to primitive value
    at String (native)
    at Function.applyStyle (/home/foobar/builds/f1af3bf9/0/foobar/foobarjs/node_modules/chalk/index.js:57:29)
    at Chalk.builder (/home/foobar/builds/f1af3bf9/0/foobar/foobarjs/node_modules/chalk/index.js:40:21)
    at writeError (/home/foobar/builds/f1af3bf9/0/foobar/foobarjs/node_modules/ember-cli/lib/ui/write-error.js:19:24)
    at UI.writeError (/home/foobar/builds/f1af3bf9/0/foobar/foobarjs/node_modules/ember-cli/lib/ui/index.js:158:3)
    at Class.module.exports.Task.extend._configuredPlugins (/home/foobar/builds/f1af3bf9/0/foobar/foobarjs/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:115:15)
    at Class.module.exports.Task.extend.setup (/home/foobar/builds/f1af3bf9/0/foobar/foobarjs/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:37:22)
    at Class.module.exports.Task.extend.run (/home/foobar/builds/f1af3bf9/0/foobar/foobarjs/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:87:10)
    at Class.module.exports.Task.extend.run (/home/foobar/builds/f1af3bf9/0/foobar/foobarjs/node_modules/ember-cli-deploy/lib/tasks/deploy.js:19:21)
    at /home/foobar/builds/f1af3bf9/0/foobar/foobarjs/node_modules/ember-cli-deploy/lib/commands/deploy.js:53:21
    at lib$rsvp$$internal$$tryCatch (/home/foobar/builds/f1af3bf9/0/foobar/foobarjs/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/foobar/builds/f1af3bf9/0/foobar/foobarjs/node_modules/rsvp/dist/rsvp.js:505:17)
    at /home/foobar/builds/f1af3bf9/0/foobar/foobarjs/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/home/foobar/builds/f1af3bf9/0/foobar/foobarjs/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by LevelbossMike** [comment]
pr for a fix: https://github.com/ember-cli-deploy/ember-cli-deploy/pull/398
