### ISSUE TITLE
Deprecation for init override.

### ISSUE THREAD

**Issue by ColtonProvias** [ember-cli-deploy/ember-cli-deploy#409]
Ember-CLI version: 2.6.2

This deprecation warning has just started appearing upon invocation of `ember deploy production`.

```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
   at Function.Addon.lookup (/drone/src/****/node_modules/ember-cli/lib/models/addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
   at Function.Addon.lookup (/drone/src/****/node_modules/ember-cli/lib/models/addon.js:896:27)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-cli-htmlbars`
   at Function.Addon.lookup (/drone/src/****/node_modules/ember-cli/lib/models/addon.js:896:27)
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `undefined`
   at Object.<anonymous> (/drone/src/****/node_modules/ember-cli-deploy/lib/tasks/read-config.js:9:23)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `undefined`
   at Object.<anonymous> (/drone/src/****/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:5:23)
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `undefined`
   at Object.<anonymous> (/drone/src/****/node_modules/ember-cli-deploy/lib/tasks/deploy.js:4:23)
```

**Comment by lukemelia** [comment]
@ColtonProvias Can you check to see if it is also happening when you run `ember build --environment=production`?

**Comment by ColtonProvias** [comment]
The first three deprecations which are for htmlbars do occur, but the last three do not.

**Comment by lukemelia** [comment]
Thanks @ColtonProvias. We should get our portion of this fixed up. If you or someone else wants to PR, that would be great. Otherwise, we'll take care of it.
