### ISSUE TITLE
Ember deploy fails to deploy in environment that builds

### ISSUE THREAD

**Issue by josephroffey** [ember-cli-deploy/ember-cli-deploy#432]
When attempting to run 'ember deploy production' in Windows 7 I am seeing:
(C:\Projects\my-project is the path of the repository I am attempting to deploy and my-submodule is an ember-addon)

ENOTEMPTY: directory not empty, rmdir 'C:\Projects\my-project\tmp\broccoli_merge_trees-output_path-OLf2xLPB.tmp\
modules\my-submodule'
Error: ENOTEMPTY: directory not empty, rmdir 'C:\Projects\my-project\tmp\broccoli_merge_trees-output_path-OLf2xL
PB.tmp\modules\my-submodule'
    at Error (native)
    at Object.fs.rmdirSync (fs.js:758:18)
    at FSMonitor._measure (C:\Projects\my-project\node_modules\heimdalljs-fs-monitor\index.js:66:21)
    at Object.rmdirSync (C:\Projects\my-project\node_modules\heimdalljs-fs-monitor\index.js:82:30)
    at rmkidsSync (C:\Projects\my-project\node_modules\quick-temp\node_modules\rimraf\rimraf.js:247:11)
    at rmdirSync (C:\Projects\my-project\node_modules\quick-temp\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (C:\Projects\my-project\node_modules\quick-temp\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (C:\Projects\my-project\node_modules\quick-temp\node_modules\rimraf\rimraf.js:216:26)
    at C:\Projects\my-project\node_modules\quick-temp\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (native)
- TypeError: path must be a string
TypeError: path must be a string
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.statSync (fs.js:844:18)
    at FSMonitor._measure (C:\Projects\my-project\node_modules\heimdalljs-fs-monitor\index.js:66:21)
    at Object.statSync (C:\Projects\my-project\node_modules\heimdalljs-fs-monitor\index.js:82:30)
    at exists (C:\Projects\my-project\node_modules\simple-git\src\util\exists.js:9:21)
    at module.exports (C:\Projects\my-project\node_modules\simple-git\src\util\exists.js:30:11)
    at module.exports (C:\Projects\my-project\node_modules\simple-git\src\index.js:10:21)
    at C:\Projects\my-project\node_modules\ember-cli-deploy-revision-data\lib\scm-data-generators\git.js:14:7
    at initializePromise (C:\Projects\my-project\node_modules\rsvp\dist\rsvp.js:588:5)
Pipeline aborted

I added some debug logs and scm-data-generators git seems to have it's path set to:

path:
   { plugin:
      Class {
        context: [Object],
        ui: [Object],
        project: [Object],
        pluginConfig: [Object] } }

whereas it is expecting a string. 

I'm not sure if this is two issues or one issue, because the ENOTEMPTY: directory not empty issue occurs each time I attempt to deploy, but can be prevented (the TypeError: path must be a string error remains) by removing and reinstalling the bower_components folder.

This project has successfully been deployed before, possibly with different versions of the node_modules/bower_components, but with no changes to the deploy.js, and as I say ember build works fine

Any ideas what might be the cause of this issue?

**Comment by lukemelia** [comment]
Hmm, is it possible there is an `ember build/serve/test` process running against the directory while you are trying to deploy?

**Comment by josephroffey** [comment]
Good idea/I hadn't checked, but no I was stopping all serves/tests in order to deploy sorry

**Comment by josephroffey** [comment]
same error (just the TypeError part again) on a clean install on my Mac

**Comment by josephroffey** [comment]
I'm sure I'm doing/have done something stupid, but would appreciate any input!

**Comment by josephroffey** [comment]
ahhh this is a duplicate of ember-cli-deploy-revision-data issue 43

https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/issues/43

**Comment by josephroffey** [comment]
deploy works with simplegit 1.57.0 as suggested in ember-cli-deploy/ember-cli-deploy-revision-data#43
submitted a pull request https://github.com/ember-cli-deploy/ember-cli-deploy-revision-data/pull/44
